services:
  - type: web
    plan: free
    name: html2md
    runtime: python
    buildCommand: pip install .[deploy]
    startCommand: gunicorn html2md.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: HOST
        value: 0.0.0.0
