services:
  - type: web
    plan: free
    name: html2md
    runtime: python
    pythonVersion: "3.11"
    buildCommand: "pip install .[deploy]"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT html2md.app:app"
