services:
  - type: web
    plan: free
    name: html2md
    runtime: python
    pythonVersion: "3.8"
    buildCommand: "pip install .[deploy]"
    startCommand: "gunicorn --workers ${WEB_CONCURRENCY:-1} --bind 0.0.0.0:$PORT html2md.app:app"
