services:
  - type: web
    plan: free
    name: html2md
    runtime: python
    repo: https://github.com/badMadeC0/html2md.git
    buildCommand: "pip install -e .[deploy]"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT html2md.app:app"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: ANTHROPIC_API_KEY
        sync: false
